from_start = '//span/a[contains(@href,"/refactoring/what-is-refactoring")]'
dirty_code = '//span/a[contains(@href,"/refactoring/technical-debt")]'
how_to = '//span/a[contains(@href,"/refactoring/how-to")]'
ru_language = '//a[@href="https://refactoring.guru/ru"]'
ua_language = '//a[@href="https://refactoring.guru/ua"]'
